### ISSUE TITLE
文本生成中前置[CLS]的问题

### ISSUE THREAD

**Issue by huhk-sysu** [dbiir/UER-py#222]
你们好，首先感谢你们的工作，让预训练语言模型能被更多人了解和使用。

第一个问题：我注意到，在你们提供的预训练GPT2模型中：
- [古诗词模型](https://huggingface.co/uer/gpt2-chinese-poem)、[对联模型](https://huggingface.co/uer/gpt2-chinese-couplet)、[文言文模型](https://huggingface.co/uer/gpt2-chinese-ancient)的输入需要在开头加入`[CLS]`。
- [通用中文模型](https://huggingface.co/uer/gpt2-chinese-cluecorpussmall)、[中文歌词模型](https://huggingface.co/uer/gpt2-chinese-lyric)则无这样的限制。

请问这是笔误，还是训练时预处理不同？

第二个问题：我注意到，在你们提供的代码中，使用LM目标进行预训练，在预处理语料时会在开头加入`[CLS]`，同样在解码时（`scripts/generate_lm.py`）也有如此设定。若是我使用HuggingFace的Transformers库加载模型（已转换），调用其`TextGenerationPipeline`，是否同样需要我在输入的文本前手动加入`[CLS]`呢？

**Comment by hhou435** [comment]
您好，我们在训练时开头都加了CLS，所以严格意义上开头都是需要加CLS，不过由于古诗对联存在对仗之类的问题，少输入一位影响会特别明显，所以在readme特别强调了，而通用模型少输入CLS对生成效果影响并不大。使用Transformers库时也是同理



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Pure White ***@***.***&gt;
发送时间: 2021年11月15日 20:17
收件人: dbiir/UER-py ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [dbiir/UER-py] 文本生成中前置[CLS]的问题 (Issue #222)





 
你们好，首先感谢你们的工作，让预训练语言模型能被更多人了解和使用。
 
第一个问题：我注意到，在你们提供的预训练GPT2模型中：
  
古诗词模型、对联模型、文言文模型的输入需要在开头加入[CLS]。 

通用中文模型、中文歌词模型则无这样的限制。 
 
请问这是笔误，还是训练时预处理不同？
 
第二个问题：我注意到，在你们提供的代码中，使用LM目标进行预训练，在预处理语料时会在开头加入[CLS]，同样在解码时（scripts/generate_lm.py）也有如此设定。若是我使用HuggingFace的Transformers库加载模型（已转换），调用其TextGenerationPipeline，是否同样需要我在输入的文本前手动加入[CLS]呢？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by huhk-sysu** [comment]
谢谢你的回答。我还有另一个问题：
假若我希望训练语言模型同时基于标题和内容进行生成，是否可以如此组织训练语料（作为preprocess.py的输入）？

```
标题1 [SEP] 篇章内容1
标题2 [SEP] 篇章内容2
标题3 [SEP] 篇章内容3
```

**Comment by P01son6415** [comment]
> 谢谢你的回答@hhou435。我还有另一个问题： 假若我希望训练语言模型同时基于标题和内容进行生成，是否可以如此组织训练语料（作为preprocess.py的输入）？
> 
> ```
> 标题1 [SEP] 篇章内容1
> 标题2 [SEP] 篇章内容2
> 标题3 [SEP] 篇章内容3
> ```
> 
> 当前预处理程序在篇章内容超出窗口范围时，后面的窗口将丢失掉标题信息，有什么好的处理方法呢？

1. 可以
2. 改用相对位置编码，不限长度，或者滑动窗口标题不动

**Comment by huhk-sysu** [comment]
> > 谢谢你的回答@hhou435。我还有另一个问题： 假若我希望训练语言模型同时基于标题和内容进行生成，是否可以如此组织训练语料（作为preprocess.py的输入）？
> > ```
> > 标题1 [SEP] 篇章内容1
> > 标题2 [SEP] 篇章内容2
> > 标题3 [SEP] 篇章内容3
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 当前预处理程序在篇章内容超出窗口范围时，后面的窗口将丢失掉标题信息，有什么好的处理方法呢？
> 
> 1. 可以
> 2. 改用相对位置编码，不限长度，或者滑动窗口标题不动

感谢，通过修改data.py，使用滑动窗口标题不动的方法解决了。
